### ISSUE TITLE
Attachement support

### ISSUE THREAD

**Issue by eliugonzalez86** [jowavp/sap-cf-mailer#10]
Hello everyone,
I'm new using node.js and CAP and I found this library that works great but does it support sending emails with attachments? 
thanks in advance

**Comment by gregorwolf** [comment]
Hi @eliugonzalez86 ,

I would suggest that you use [SAP Cloud SDK Mail Client](https://sap.github.io/cloud-sdk/docs/js/features/mail-client). As it's based on nodemailer check their documentation for [attachments](https://nodemailer.com/message/attachments/).

Best Regards
Gregor
